### ISSUE TITLE
Not working anymore. 

### ISSUE THREAD

**Issue by bazwilliams** [kylegordon/pypollen#3]
Not sure if the API this library is using is working anymore. For the last week or so I’ve been receiving timeouts on accessing the server. I can’t access it myself. 

Unfortunately it’s not easy for me to tell when it last worked.

**Comment by kylegordon** [comment]
https://socialpollencount.co.uk/ and embed in https://www.benadryl.co.uk/social-pollen-count are both offline and not responding.

**Comment by bazwilliams** [comment]
Awesome work! 😎 

I’ll bump my code so it at least exits in a timely way. 

Hopefully the upstream service comes back.

**Comment by kylegordon** [comment]
:+1:
